### PR TITLE
Set out path option added

### PR DESCRIPTION
**Pull request by Taxxx**
Added option to set the output path to save the generated pdf files

### CODE REVIEW

**Comment by arve0** [comment]
Hi!
I see that the pdfs will be called doc0.pdf, doc1.pdf, doc2.pdf, ...

What do you think about spawning several processes of nodepdf-series (name crashes)? And what about overwriting in general?

A test or two would be nice also.

**Comment by Taxxx** [comment]
Hi @arve0 I applied changes to prevent name crashes - overwriting and I added a test too

**Comment by arve0** [comment]
:+1: 

Will merge when I'm back at the computer.

**Comment by Taxxx** [comment]
@arve0 do you have some feedback?

**Comment by arve0** [comment]
Skimmed through. Looks good!

I'm currently on vacation, I'll be back next week.

**Comment by arve0** [comment]
Thanks for submitting :octocat:

**Comment by arve0** [comment]
Released in v1.2.0

**Pull request merged**
